### PR TITLE
Handle trailing commans, comments and existing keys in appsettings

### LINKED ISSUE #8: Insufficient error handling for `AppSettingsRewriter`
### Description of the bug

* AppSettingsRewriter throws an exception on trailing comma, this should be ignored.

```
Unhandled exception: System.Text.Json.JsonReaderException: The JSON object contains a trailing comma at the end which is not supported in this mode. Change the reader options. LineNumber: 28 | BytePositionInLine: 2.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
   at Altinn.Studio.Cli.v7Tov8.AppSettingsRewriter.AppSettingsRewriter..ctor(String appSettingsFolder) in /_/src/altinn-studio-cli/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:line 29
   at Altinn.Studio.Cli.Program.UpgradeAppSettings(String appSettingsFolder) in /_/src/altinn-studio-cli/Program.cs:line 271
   at Altinn.Studio.Cli.Program.<>c__DisplayClass1_0.<<Main>b__11>d.MoveNext() in /_/src/altinn-studio-cli/Program.cs:line 133
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

* AppSettingsRewriter throws an exception if there are comments present, maybe it should be ignored instead?

```
Unhandled exception: System.Text.Json.JsonReaderException: '/' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 55 | BytePositionInLine: 2.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, JsonTokenType tokenType)
   at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOptions, JsonDocumentOptions documentOptions)
   at Altinn.Studio.Cli.v7Tov8.AppSettingsRewriter.AppSettingsRewriter..ctor(String appSettingsFolder) in /_/src/altinn-studio-cli/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:line 29
   at Altinn.Studio.Cli.Program.UpgradeAppSettings(String appSettingsFolder) in /_/src/altinn-studio-cli/Program.cs:line 271
   at Altinn.Studio.Cli.Program.<>c__DisplayClass1_0.<<Main>b__11>d.MoveNext() in /_/src/altinn-studio-cli/Program.cs:line 133
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

* AppSettingsRewriter should give a helpful error message if there are duplicate keys instead of throwing an exception.

```
Unhandled exception: System.ArgumentException: An item with the same key has already been added. Key: FeatureManagement (Parameter 'propertyName')
   at System.Text.Json.ThrowHelper.ThrowArgumentException_DuplicateKey(String paramName, String propertyName)
   at System.Text.Json.Nodes.JsonObject.InitializeDictionary()
   at System.Text.Json.Nodes.JsonObject.TryGetPropertyValue(String propertyName, JsonNode& jsonNode)
   at Altinn.Studio.Cli.v7Tov8.AppSettingsRewriter.AppSettingsRewriter.RewriteRemoveHiddenDataSetting(String fileName, JsonObject settings) in /_/src/altinn-studio-cli/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:line 82
   at Altinn.Studio.Cli.v7Tov8.AppSettingsRewriter.AppSettingsRewriter.Upgrade() in /_/src/altinn-studio-cli/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:line 56
   at Altinn.Studio.Cli.Program.UpgradeAppSettings(String appSettingsFolder) in /_/src/altinn-studio-cli/Program.cs:line 272
   at Altinn.Studio.Cli.Program.<>c__DisplayClass1_0.<<Main>b__11>d.MoveNext() in /_/src/altinn-studio-cli/Program.cs:line 133
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Steps To Reproduce

.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tjololo**
## Description
Fixes #8 

## Related Issue(s)
- #{issue number}

## Verification
- [ ] **Your** code builds clean without any errors or warnings
- [ ] Manual testing done (required)
- [ ] Relevant automated test added (if you find this hard, leave it and we'll help out)
- [ ] All tests run green

## Documentation
- [ ] User documentation is updated with a separate linked PR in [altinn-studio-docs.](https://github.com/Altinn/altinn-studio-docs) (if applicable)

### CODE REVIEW

File: src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs [hunk 1]
```diff
@@ -100,10 +102,23 @@ private void RewriteRemoveHiddenDataSetting(string fileName, JsonObject settings
...
+        }
 
+        if (appSettingsObject.ContainsKey("RequiredValidation"))
+        {
+            warnings.Add($"RequiredValidation already exists in AppSettings, skipping. Tool would have set the value to: {removeHiddenDataValue} in {fileName}");
+        }
+        else
+        {
+            appSettingsObject.Add("RequiredValidation", removeHiddenDataValue);
+        }
```
Comment (bjosttveit) [inline src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:122]: Nice catch! This needs to be here as well. However, this will not fix the uncaught exception with duplicate keys, as it was caused by existing duplicate keys in appsettings which throws an error when trying to get any property from the json file. If you look at the exception thrown, it actually happens already at line 82 (or 84 here), on:

```cs
settings.TryGetPropertyValue("AppSettings", out var appSettingsNode);
```

The way I solved this in the frontend upgrade tool was by adding a try-catch block around this like here, in `LayoutSetUpgrader.cs:39`

```cs
// Read dataTypes array
JsonNode? dataTypes;
try
{
  appMetaJsonObject.TryGetPropertyValue("dataTypes", out dataTypes);
}
catch (Exception e)
{
  // Duplicate keys in the object will throw an exception here
  warnings.Add($"Unable to parse applicationmetadata.json, skipping layout sets upgrade, error: {e.Message}");
  return;
}
```

File: src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs [hunk 2]
```diff
@@ -89,36 +89,48 @@ private void RewriteRemoveHiddenDataSetting(string fileName, JsonObject settings
...
 
         // Look for "RemoveHiddenDataPreview" property
-        appSettingsObject.TryGetPropertyValue("RemoveHiddenDataPreview", out var removeHiddenDataPreviewNode);
-        if (removeHiddenDataPreviewNode is not JsonValue removeHiddenDataPreviewValue)
+        try
         {
-            // No "RemoveHiddenDataPreview" property found, nothing to change
-            return;
-        }
+            appSettingsObject.TryGetPropertyValue("RemoveHiddenDataPreview", out var removeHiddenDataPreviewNode);
```
Comment (bjosttveit) [inline src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:94]: Tested this, it still fails on line 84, that is where the error occurs:
```
Unhandled exception: System.ArgumentException: An item with the same key has already been added. Key: FeatureManagement (Parameter 'propertyName')
   at System.Text.Json.ThrowHelper.ThrowArgumentException_DuplicateKey(String paramName, String propertyName)
   at System.Text.Json.Nodes.JsonObject.InitializeDictionary()
   at System.Text.Json.Nodes.JsonObject.TryGetPropertyValue(String propertyName, JsonNode& jsonNode)
   at Altinn.Studio.Cli.Upgrade.Backend.v7Tov8.AppSettingsRewriter.AppSettingsRewriter.RewriteRemoveHiddenDataSetting(String fileName, JsonObject settings) in /_/src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:line 84
   at Altinn.Studio.Cli.Upgrade.Backend.v7Tov8.AppSettingsRewriter.AppSettingsRewriter.Upgrade() in /_/src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs:line 58
   at Altinn.Studio.Cli.Upgrade.Backend.v7Tov8.BackendUpgrade.BackendUpgrade.UpgradeAppSettings(String appSettingsFolder) in /_/src/altinn-studio-cli/Upgrade/Backend/v7Tov8/BackendUpgrade/BackendUpgrade.cs:line 257
   at Altinn.Studio.Cli.Upgrade.Backend.v7Tov8.BackendUpgrade.BackendUpgrade.<>c__DisplayClass0_0.<<GetUpgradeCommand>b__10>d.MoveNext() in /_/src/altinn-studio-cli/Upgrade/Backend/v7Tov8/BackendUpgrade/BackendUpgrade.cs:line 134

```

Comment (tjololo) [reply src/altinn-studio-cli/Upgrade/Backend/v7Tov8/AppSettingsRewriter/AppSettingsRewriter.cs]: Sorry, tested in a nested object and got a error on another line 🙈 should be fixed now

**Review by bjosttveit — APPROVED** [review]
Zero crashes in tt02 🥳
